site_name: "CiviCRM - Guia de l'usuari"
site_url: https://docs.civicrm.org/user/ca/latest/
repo_url: https://github.com/babu-cat/civicrm-user-guide-ca
site_description: 'Una guia per als usuaris del CiviCRM.'
site_author: 'La comunitat de CiviCRM'
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

pages:
- Inici: 'index.md'
- Introducció (untranslated):
    - 'Què és CiviCRM?': 'introduction/what-is-civicrm.md'
    - 'Is CiviCRM for You?': 'introduction/is-civicrm-for-you.md'
    - 'Real World Examples': 'introduction/real-world-examples.md'
    - 'Components': 'introduction/components.md'
    - 'Extensions': 'introduction/extensions.md'
    - 'Who is CiviCRM?': 'introduction/who-is-civicrm.md'
- Configuració inicial (untranslated):
    - 'Installation and basic set-up': 'initial-set-up/installation-and-basic-set-up.md'
    - 'Customizing the user interface': 'initial-set-up/customizing-the-user-interface.md'
    - 'Dates': 'initial-set-up/dates.md'
    - 'Addresses': 'initial-set-up/addresses.md'
    - 'Mapping': 'initial-set-up/mapping.md'
    - 'Users contacts': 'initial-set-up/users-contacts.md'
    - 'Permissions and access control': 'initial-set-up/permissions-and-access-control.md'
    - 'Resource urls': 'initial-set-up/resource-urls.md'
    - 'Logging': 'initial-set-up/change-logging.md'
    - 'Error handling': 'initial-set-up/error-handling.md'
    - 'Scheduled Jobs': 'initial-set-up/scheduled-jobs.md'
- La interfície d'usuari (untranslated):
    - 'Menu, dashboard and dashlets': 'the-user-interface/menu-dashboard-and-dashlets.md'
    - 'Searching': 'the-user-interface/searching.md'
    - 'Undelete': 'the-user-interface/undelete.md'
- Organitzant les vostres dades (untranslated):
    - 'Overview': 'organising-your-data/overview.md'
    - 'Mapping your data': 'organising-your-data/mapping-your-data.md'
    - 'Contacts': 'organising-your-data/contacts.md'
    - 'Groups and tags': 'organising-your-data/groups-and-tags.md'
    - 'Smart groups': 'organising-your-data/smart-groups.md'
    - 'Activities': 'organising-your-data/activities.md'
    - 'Relationships': 'organising-your-data/relationships.md'
    - 'Creació de camps personalitzats': 'organising-your-data/creating-custom-fields.md'
    - 'Profiles': 'organising-your-data/profiles.md'
- Fluxos de treball comuns (partially translated):
    - 'Importació de dades en el CiviCRM (untranslated)': 'common-workflows/importing-data-into-civicrm.md'
    - 'Exportació dels vostres contactes (untranslated)': 'common-workflows/exporting-your-contacts.md'
    - 'Cerca i combinació de duplicats (untranslated)': 'common-workflows/deduping-and-merging.md'
    - 'Tokens i combinació de correspondència (untranslated)': 'common-workflows/tokens-and-mail-merge.md'
    - 'Comunicacions per correu postal': 'common-workflows/postal-mail-communications.md'
    - 'Automatitzant tasques (untranslated)': 'common-workflows/automating-tasks.md'
- Contribucions (partially translated):
    - 'What is CiviContribute? (untranslated)': 'contributions/what-is-civicontribute.md'
    - 'Conceptes claus i configuracions': 'contributions/key-concepts-and-configurations.md'
    - 'Online contributions (untranslated)': 'contributions/online-contributions.md'
    - 'Offline fundraising (untranslated)': 'contributions/offline-fundraising.md'
    - 'Manual entry of contributions (untranslated)': 'contributions/manual-entry-of-contributions.md'
    - 'Finding and viewing contributions (untranslated)': 'contributions/finding-and-viewing-contributions.md'
    - 'Manual receipts and thank-you letters (untranslated)': 'contributions/manual-receipts-and-thank-yous.md'
    - 'Reports and analysis (untranslated)': 'contributions/reports-and-analysis.md'
    - 'Soft credits (untranslated)': 'contributions/soft-credits.md'
    - 'Personal Campaign Pages (untranslated)': 'contributions/personal-campaign-pages.md'
    - 'Accounting Integration (untranslated)': 'contributions/accounting-integration.md'
    - 'Payment processors (untranslated)': 'contributions/payment-processors.md'
    - 'Invoicing (untranslated)': 'contributions/invoicing.md'
    - 'Sales tax and VAT (untranslated)': 'contributions/sales-tax-and-vat.md'
    - 'Premiums (untranslated)': 'contributions/premiums.md'
    - 'Widgets (untranslated)': 'contributions/widgets.md'
- Compromisos (untranslated):
    - 'What is CiviPledge?': 'pledges/what-is-civipledge.md'
    - 'What you need to know': 'pledges/what-you-need-to-know.md'
    - 'Set-up': 'pledges/set-up.md'
    - 'Everyday tasks': 'pledges/everyday-tasks.md'
    - 'Pledges Reports and Analysis': 'pledges/pledges-reports-and-analysis.md'
- Esdeveniments (partially translated):
    - 'What is CiviEvent? (untranslated)': 'events/what-is-civievent.md'
    - 'Event planning and management (untranslated)': 'events/event-planning-and-management.md'
    - "Creació d'esdeveniments": 'events/creating-an-event.md'
    - "Registre en línia d'esdeveniments (untranslated)": 'events/online-event-registration.md'
    - 'Integrating events with your website (untranslated) (untranslated) (untranslated)': 'events/integrating-events-with-your-website.md'
    - "Registre manual d'esdeveniments (untranslated)": 'events/manual-event-registration.md'
    - 'Keeping track of events and participants (untranslated)': 'events/keeping-track-of-events-and-participants.md'
    - 'Complex event fees (untranslated)': 'events/complex-event-fees.md'
    - "Plantilles d'esdeveniments": 'events/event-templates.md'
    - 'Reports (untranslated)': 'events/reports.md'
    - 'Custom data for events (untranslated)': 'events/custom-data-for-events.md'
    - 'Repeating Events (untranslated)': 'events/repeating-events.md'
- Membres (untranslated):
    - 'What is CiviMember': 'membership/what-is-civimember.md'
    - 'Defining memberships': 'membership/defining-memberships.md'
    - 'Online membership sign up': 'membership/online-membership-sign-up.md'
    - 'Manual entry of memberships': 'membership/manual-entry-of-memberships.md'
    - 'Membership price sets': 'membership/membership-price-sets.md'
    - 'Finding and viewing memberships': 'membership/finding-and-viewing-memberships.md'
    - 'Membership Reports': 'membership/membership-reports.md'
    - 'Renewals': 'membership/renewals.md'
    - 'Cancelling and expiring memberships': 'membership/cancelling-and-expiring-memberships.md'
    - 'Making member only websites': 'membership/making-member-only-websites.md'
- Correu electrònic (partially translated):
    - 'What is CiviMail? (untranslated)': 'email/what-is-civimail.md'
    - 'What You Need To Know (untranslated)': 'email/what-you-need-to-know.md'
    - 'Set-up (untranslated)': 'email/set-up.md'
    - 'Maintaining Healthy Email Lists (untranslated)': 'email/maintaining-healthy-email-lists.md'
    - 'Everyday tasks (untranslated)': 'email/everyday-tasks.md'
    - 'Mass mailings using CiviMail': 'email/mass-mailings-using-civimail.md'
    - 'Reports and analysis (untranslated)': 'email/reports-and-analysis.md'
    - 'Scheduled reminders (untranslated)': 'email/scheduled-reminders.md'
    - 'CiviMail A/B Testing (untranslated)': 'email/civimail-ab-testing.md'
    - 'Message templates (untranslated)': 'email/message-templates.md'
- SMS (missatges de text) (untranslated):
    - 'What is SMS?': 'sms-text-messaging/what-is-sms.md'
    - 'Set-up': 'sms-text-messaging/set-up.md'
    - 'Everyday tasks': 'sms-text-messaging/everyday-tasks.md'
    - 'Reports and Analysis (SMS)': 'sms-text-messaging/reports-and-analysis-sms.md'
- Informes (untranslated):
    - 'What is CiviReport?': 'reporting/what-is-civireport.md'
    - 'What You Need To Know': 'reporting/what-you-need-to-know.md'
    - 'Set-up': 'reporting/set-up.md'
    - 'Everyday Tasks': 'reporting/everyday-tasks.md'
- Gestió de casos (untranslated):
    - 'What is CiviCase?': 'case-management/what-is-civicase.md'
    - 'What You Need To Know': 'case-management/what-you-need-to-know.md'
    - 'Set-up': 'case-management/set-up.md'
    - 'Everyday Tasks': 'case-management/everyday-tasks.md'
    - 'Reports and analysis': 'case-management/reports-and-analysis.md'
- Campanyes (untranslated):
    - 'What is CiviCampaign?': 'campaign/what-is-civicampaign.md'
    - 'What You Need To Know': 'campaign/what-you-need-to-know.md'
    - 'Set-up': 'campaign/set-up.md'
    - 'Everyday tasks': 'campaign/everyday-tasks.md'
    - 'Reports and analysis': 'campaign/reports-and-analysis.md'
- Enquestes (untranslated):
    - 'What is CiviSurvey?': 'survey/what-is-civisurvey.md'
    - 'What You Need To Know': 'survey/what-you-need-to-know.md'
    - 'Set-up': 'survey/set-up.md'
    - 'Everyday Tasks': 'survey/everyday-tasks.md'
    - 'Reports and analysis': 'survey/reports-and-analysis.md'
    - 'What is GOTV (Voter Tracking)?': 'survey/what-is-gotv-voter-tracking.md'
- Peticions (untranslated):
    - 'What is CiviPetition?': 'petition/what-is-civipetition.md'
    - 'What You Need To Know': 'petition/what-you-need-to-know.md'
    - 'Set-up': 'petition/set-up.md'
    - 'Everyday Tasks': 'petition/everyday-tasks.md'
    - 'Reports and analysis': 'petition/reports-and-analysis.md'
- Civic Engagement (untranslated):
    - 'What is CiviEngage?': 'civic-engagement/what-is-civiengage.md'
    - 'What You Need To Know': 'civic-engagement/what-you-need-to-know.md'
    - 'Set-up': 'civic-engagement/set-up.md'
    - 'Everyday Tasks': 'civic-engagement/everyday-tasks.md'
    - 'Reports and analysis': 'civic-engagement/reports-and-analysis.md'
- Grants (untranslated):
    - 'What is CiviGrant?': 'grants/what-is-civigrant.md'
    - 'What You Need To Know': 'grants/what-you-need-to-know.md'
    - 'Set-up': 'grants/set-up.md'
    - 'Everyday tasks': 'grants/every-day-tasks.md'
    - 'Reports and analyis': 'grants/reports-and-analysis.md'
- La comunitat de CiviCRM (untranslated):
    - 'The CiviCRM Community': 'the-civicrm-community/the-civicrm-community.md'
    - 'Bug Reporting': 'the-civicrm-community/bug-reporting.md'
    - 'Localising CiviCRM': 'the-civicrm-community/localising-civicrm.md'
    - 'Contribuir a aquesta guia': 'the-civicrm-community/contributing-to-this-manual.md'
    - 'Asking for help in Chat': 'the-civicrm-community/asking-for-help-in-chat.md'
- Annexos (untranslated):
    - 'Història d&apos;aquest llibre': 'appendices/history-of-this-book.md'
    - 'Programari lliure?': 'appendices/free-software.md'
    - 'Glosari': 'appendices/glossary.md'
    - 'Crèdits': 'appendices/credits.md'
